"""Universal LLM-call contract.

``LLMClient`` is the SDK-agnostic structured-completion primitive both
the policy gate (``app/gate/policy/gate.py``) and the eval harness's
judge layer (``eval/judge.py``) consume. Concrete adapters live in
``app/llm/`` — one per provider.

This module has zero infrastructure dependencies (preserves the
``core/`` boundary): only Pydantic, typing, and stdlib imports. Concrete
adapters in ``app/llm/`` are the only modules permitted to import an
LLM SDK class.
"""

from __future__ import annotations

from typing import Generic, Protocol, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T", bound=BaseModel)


class TokenUsage(BaseModel):
    """Neutral token-usage primitive returned by every adapter.

    Adapters fill ``cost_usd`` from a per-provider pricing table when
    the model id is known; ``None`` when it isn't (e.g., a model id
    not in the project's pricing table). Callers that require cost
    must check before persisting.

    Args:
        prompt_tokens: Input tokens consumed by the call.
        completion_tokens: Output tokens generated by the call.
        total_tokens: Sum reported by the provider (may differ from
            ``prompt + completion`` for models with tool/cache tokens).
        model: Concrete model id the call resolved against
            (e.g., ``"gpt-4o-2024-08-06"``).
        cost_usd: Computed dollar cost from the adapter's pricing
            table, or ``None`` if the model is unknown to the table.
    """

    model_config = ConfigDict(strict=True, frozen=True)

    prompt_tokens: int = Field(ge=0)
    completion_tokens: int = Field(ge=0)
    total_tokens: int = Field(ge=0)
    model: str = Field(min_length=1)
    cost_usd: float | None = Field(default=None, ge=0.0)


class CompletionResult(BaseModel, Generic[T]):
    """Wrap a parsed structured completion with its operational metadata.

    ``parsed`` is the validated Pydantic instance the caller asked for.
    ``usage`` and ``latency_ms`` are universal observability fields the
    audit layer (``PolicyGateOutput.token_cost``) and the eval layer
    (cost tracking, latency telemetry) both record.

    Args:
        parsed: Pydantic-validated response; type narrowed by the
            ``response_format`` argument the caller passed.
        usage: Token usage + model id reported by the provider.
        latency_ms: Wall-clock duration of the call in milliseconds.
    """

    model_config = ConfigDict(strict=True, frozen=True, arbitrary_types_allowed=True)

    parsed: T
    usage: TokenUsage
    latency_ms: float = Field(ge=0.0)


class LLMClient(Protocol):
    """SDK-agnostic structured-completion contract.

    Implementations live in ``app/llm/`` (one per provider). Consumers
    (``PolicyGate``, ``llm_judge``) accept this protocol; they never
    import an LLM SDK directly. Swapping providers is a constructor
    swap at the wiring edge.

    All implementations are async — LLM calls are I/O-bound and the
    primary callers (FastAPI route handler, eval dimensions) are
    async-native.
    """

    async def complete_structured(
        self,
        *,
        system: str,
        user: str,
        response_format: type[T],
    ) -> CompletionResult[T]:
        """Issue a structured-completion call and return parsed + metadata.

        Args:
            system: System message setting the model's role.
            user: User message containing the task.
            response_format: Pydantic model class the response must
                validate against. Adapters translate this into the
                provider's structured-output mechanism (OpenAI strict
                JSON schema, Anthropic tool input schema, etc.).

        Returns:
            ``CompletionResult[T]`` with parsed instance, token usage,
            and call latency.

        Raises:
            RuntimeError: Provider returned no parseable structured
                output (e.g., refusal, schema-validation failure at
                the SDK layer). Adapters re-raise SDK-specific errors
                as ``RuntimeError`` to keep the error surface
                provider-neutral.
        """
        ...
