"""Scenario configuration schema for the ATO Reasoner synthetic event generator.

ScenarioConfig is the contract between scenario YAML files and the generator
implementation. Each YAML file in generator/scenarios/ is loaded and validated against
this schema before any events are generated.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from core.actions import DecisionAction

# ---------------------------------------------------------------------------
# Generation parameter schemas
# ---------------------------------------------------------------------------


class DeviceConsistency(StrEnum):
    """Device fingerprint consistency mode for a generated event stream.

    Controls whether the device fingerprint field stays constant, varies
    partially, or rotates entirely across events for the same account.

    Attributes:
        STABLE: Same fingerprint for every event. Models a single device
            with no hardware or software changes.
        PARTIAL: Mostly-matching fingerprint across events. Models a browser
            update, OS upgrade, or the same user on two similar devices.
        ROTATING: Distinct fingerprint per rotation cycle. Models attacker
            infrastructure cycling identifiers to evade detection.
    """

    STABLE = "stable"
    PARTIAL = "partial"
    ROTATING = "rotating"


class RotationIntensity(StrEnum):
    """Frequency at which source IP or ASN rotates across generated events.

    Applies independently to IP addresses and ASNs via the NetworkConfig
    ip_rotation and asn_rotation fields.

    Attributes:
        NONE: No rotation. A single address is used for the entire run.
        LOW: Infrequent rotation. Consistent with a residential ISP
            occasionally reassigning an address.
        MODERATE: Moderate rotation. Consistent with a mobile user
            moving between networks.
        HIGH: Per-event rotation. Characteristic of proxy or VPN
            infrastructure cycling addresses to evade IP-based detection.
    """

    NONE = "none"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class GeoMobility(StrEnum):
    """Geographic mobility pattern for a generated event stream.

    Controls how the geo.city and geo.country fields vary across consecutive
    events for the same account.

    Attributes:
        STATIC: All events originate from a single city. No geographic
            movement. Models a user who always logs in from one location.
        REGIONAL: Events originate from cities within the same geographic
            region. Models normal travel within a country or continent.
        ERRATIC: Events originate from cities across multiple continents.
            When combined with GeoConfig.impossible_travel=True, consecutive
            events for the same account are placed in regions separated by
            intercontinental distances, producing physically impossible travel
            speeds.
    """

    STATIC = "static"
    REGIONAL = "regional"
    ERRATIC = "erratic"


class AuthMethod(StrEnum):
    """Authentication method used in generated events.

    A subset of the full AuthMethod enum in core.account_takeover.events —
    covers the four methods exercised by the current scenario definitions.

    Attributes:
        PASSWORD: Standard username/password credential pair.
        MFA_TOTP: Time-based One-Time Password (RFC 6238). A short-lived
            numeric code generated by an authenticator app, used as a second
            factor alongside the primary credential.
        MFA_PUSH: Push notification sent to a registered mobile device as a
            second factor. The user approves the notification to complete
            authentication.
        SSO: Single Sign-On via a federated identity provider using SAML or
            OIDC. Used for service accounts and high-velocity legitimate
            scenarios.
    """

    PASSWORD = "PASSWORD"
    MFA_TOTP = "MFA_TOTP"
    MFA_PUSH = "MFA_PUSH"
    SSO = "SSO"


class VelocityConfig(BaseModel):
    """Velocity parameters controlling event rate and burst behavior.

    Attributes:
        events_per_minute: Target event rate for this scenario.
        jitter_factor: Timing randomness as a fraction of the inter-event interval.
            0.0 = perfectly regular; 1.0 = up to 100% timing variation.
        burst_factor: Velocity multiplier applied during burst windows.
        burst_duration_s: Duration of each burst window in seconds. None = no bursts.
    """

    model_config = ConfigDict(frozen=True)

    events_per_minute: float = Field(gt=0, description="Target event rate")
    jitter_factor: float = Field(default=0.2, ge=0.0, le=1.0)
    burst_factor: float = Field(default=1.0, gt=0)
    burst_duration_s: int | None = Field(default=None, ge=1)


class DeviceConfig(BaseModel):
    """Device fingerprint behavior parameters.

    Attributes:
        fingerprint_count: Number of distinct device fingerprints to cycle through.
        consistency: How device fingerprints are selected across events.
        partial_match_score: For PARTIAL mode, forces device_consistency_score to
            this value. Simulates a browser update or OS upgrade on the same device.
    """

    model_config = ConfigDict(frozen=True)

    fingerprint_count: int = Field(default=1, ge=1)
    consistency: DeviceConsistency = DeviceConsistency.STABLE
    partial_match_score: float | None = Field(default=None, ge=0.0, le=1.0)


class NetworkConfig(BaseModel):
    """Network (IP and ASN) behavior parameters.

    Attributes:
        ip_rotation: How frequently the source IP address changes.
        asn_rotation: How frequently the source ASN changes.
        use_known_bad_asn: If True, events originate from synthesized known-bad
            ASN ranges. Sets a pre-computed risk signal in the generated event.
    """

    model_config = ConfigDict(frozen=True)

    ip_rotation: RotationIntensity = RotationIntensity.NONE
    asn_rotation: RotationIntensity = RotationIntensity.NONE
    use_known_bad_asn: bool = False


class GeoConfig(BaseModel):
    """Geographic behavior parameters.

    Attributes:
        mobility: Movement pattern across events.
        impossible_travel: If True, consecutive events are placed in locations
            that are physically impossible to travel between in the elapsed time.
        min_travel_speed_kmh: Minimum speed (km/h) enforced between consecutive
            locations. Values > ~900 are physically impossible for commercial travel.
        country_count: Number of distinct countries represented in the event stream.
    """

    model_config = ConfigDict(frozen=True)

    mobility: GeoMobility = GeoMobility.STATIC
    impossible_travel: bool = False
    min_travel_speed_kmh: float | None = Field(default=None, ge=0.0)
    country_count: int = Field(default=1, ge=1)


class AuthConfig(BaseModel):
    """Authentication behavior parameters.

    Attributes:
        outcome_weights: Sampling weights for authentication outcomes.
            Keys must be a subset of: SUCCESS, FAILURE, TIMEOUT, BLOCKED.
            Values are relative weights (do not need to sum to 1.0).
        method: Authentication method used in all events for this scenario.
    """

    model_config = ConfigDict(frozen=True)

    outcome_weights: dict[str, float] = Field(
        description="Relative sampling weights for auth outcomes"
    )
    method: AuthMethod = AuthMethod.PASSWORD


class AdversarialConfig(BaseModel):
    """Adversarial payload injection parameters.

    Used exclusively by the adversarial_probe scenario. Controls injection of
    prompt injection payloads into event fields and schema violation attempts.

    Attributes:
        user_agent_injection: If True, the user_agent field contains an injection
            payload.
        user_agent_payload: The exact string to inject into the user_agent field.
        metadata_injection: If True, additional metadata fields contain injection
            payloads.
        schema_violation_attempt: If True, some events are malformed to test schema
            validation in the ingestion layer.
    """

    model_config = ConfigDict(frozen=True)

    user_agent_injection: bool = False
    user_agent_payload: str | None = None
    metadata_injection: bool = False
    schema_violation_attempt: bool = False


class GenerationConfig(BaseModel):
    """Complete event generation parameters for a scenario.

    Attributes:
        user_count: Number of distinct user accounts to simulate.
        events_per_run: Total events to generate in a single CLI run.
        novel_entity: If True, all simulated users have fewer than
            NOVEL_ENTITY_MIN_EVENTS historical events. Triggers the
            novel-entity routing rule in the enforcement layer.
        velocity: Event rate and burst behavior.
        device: Device fingerprint behavior.
        network: IP and ASN behavior.
        geo: Geographic behavior.
        auth: Authentication method and outcome distribution.
        adversarial: Adversarial payload injection. Only set for adversarial_probe.
    """

    model_config = ConfigDict(frozen=True)

    user_count: int = Field(default=1, ge=1)
    events_per_run: int = Field(default=50, ge=1)
    novel_entity: bool = False
    velocity: VelocityConfig
    device: DeviceConfig
    network: NetworkConfig = Field(default_factory=NetworkConfig)
    geo: GeoConfig = Field(default_factory=GeoConfig)
    auth: AuthConfig
    adversarial: AdversarialConfig | None = None


# ---------------------------------------------------------------------------
# Top-level scenario configuration
# ---------------------------------------------------------------------------


class ScenarioConfig(BaseModel):
    """Configuration for a named ATO Reasoner event generation scenario.

    Scenario configs are loaded from YAML files in generator/scenarios/ at generator
    startup. Each YAML filename stem must match the scenario_id field.

    Attributes:
        scenario_id: Machine-readable identifier. Must match the YAML filename stem.
        display_name: Human-readable name for logging and evaluation reports.
        description: What this scenario represents and what system behavior it tests.
        expected_actions: Acceptable enforcement outputs for this scenario. Used by
            the evaluation harness to assert correct pipeline behavior. An output
            not in this list is a failing test.
        generation: Event generation parameters.
        notes: Design notes, calibration rationale, and edge cases. Not used by
            the generator — for documentation purposes only.

    Example::

        config = ScenarioConfig.model_validate(yaml.safe_load(path.read_text()))
        assert config.scenario_id == path.stem
    """

    model_config = ConfigDict(frozen=True)

    scenario_id: str
    display_name: str
    description: str
    expected_actions: list[DecisionAction]
    generation: GenerationConfig
    notes: str | None = None
