"""ATO Reasoner login event schema and authentication domain enums.

LoginEvent satisfies the framework Observation protocol via the computed
entity_id field, entity_type, event_id, and timestamp. entity_id is derived
deterministically from account_id using UUID5 so that any caller can
reproduce the framework identity from the domain business key without a
registry lookup.

Framework fields (route, reasoner_context, fast_path_rationale, gate_context)
default to unassembled values. The domain assembler (assembler.py) populates
them from scorer output and computed features before framework submission.
Submitting an event with default framework fields to the DecisionLedger
framework is a contract violation — use assembler.build_observation() instead.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, computed_field

from core.observation import GateContext, ReasonerContext
from core.routes import GateRoute

# Stable UUID5 namespace for ATO Reasoner account entity identifiers.
# UUID5(_ATO_ACCOUNT_NS, account_id) produces a reproducible, opaque
# framework UUID for any account business key.
_ATO_ACCOUNT_NS: UUID = UUID("8a1f9b2e-4c3d-5e6f-7a8b-9c0d1e2f3a4b")


class AuthMethod(StrEnum):
    """Authentication method used for a login attempt.

    Attributes:
        PASSWORD: Standard username/password credential pair.
        MFA_TOTP: Time-based One-Time Password (RFC 6238). A short-lived
            numeric code generated by an authenticator app, used as a second
            factor alongside the primary credential.
        MFA_PUSH: Push notification sent to a registered mobile device as a
            second factor. The user approves the notification to complete
            authentication.
        SSO: Single Sign-On via a federated identity provider using SAML or
            OIDC. The provider vouches for the user's identity.
        PASSKEY: FIDO2/WebAuthn passkey — phishing-resistant, passwordless
            credential bound to a hardware authenticator or device biometric.
        MAGIC_LINK: One-time authentication link delivered to a verified email
            address. The link is single-use and time-limited.
    """

    PASSWORD = "PASSWORD"
    MFA_TOTP = "MFA_TOTP"
    MFA_PUSH = "MFA_PUSH"
    SSO = "SSO"
    PASSKEY = "PASSKEY"
    MAGIC_LINK = "MAGIC_LINK"


class AuthOutcome(StrEnum):
    """Outcome of a login authentication attempt.

    Attributes:
        SUCCESS: Authentication completed; a session was created.
        FAILURE: Authentication rejected — incorrect credential, OTP mismatch,
            or biometric failure.
        TIMEOUT: Authentication request expired before the user completed the
            challenge. Most common in MFA_PUSH flows where the user does not
            respond to the push notification.
        BLOCKED: Request rejected by a pre-authentication control — an IP
            block, rate limiter, or a prior BLOCK decision from the pipeline.
    """

    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    TIMEOUT = "TIMEOUT"
    BLOCKED = "BLOCKED"


class Geolocation(BaseModel):
    """Geographic location data attached to a login event.

    Attributes:
        latitude: Latitude in decimal degrees.
        longitude: Longitude in decimal degrees.
        country: ISO 3166-1 alpha-2 country code (e.g., "US", "DE").
        city: City name as resolved by the geolocation provider.
        asn: Autonomous System Number (e.g., "AS15169").
    """

    model_config = ConfigDict(strict=True, frozen=True)

    latitude: float
    longitude: float
    country: str
    city: str
    asn: str


class LoginEvent(BaseModel):
    """Validated login event entering the ATO Reasoner pipeline.

    Satisfies the framework Observation protocol. entity_id is derived
    deterministically from account_id via UUID5 — no registry required.
    account_id is retained as a domain attribute for application-layer use
    (Redis keys, log labels, query filters).

    Attributes:
        event_id: Unique identifier for this event instance.
        entity_type: Framework subject classification. Always "account" for
            ATO Reasoner login events.
        timestamp: When the login attempt occurred (UTC).
        account_id: Stable ATO domain business key for the account.
        session_id: Identifier for the current session.
        ip_address: Source IP address (IPv4 or IPv6).
        geolocation: Geographic location derived from the source IP.
        device_fingerprint: Stable device identifier.
        user_agent: HTTP User-Agent string.
        auth_method: Authentication method used.
        outcome: Result of the authentication attempt.
        route: Routing decision produced by the ATO domain pipeline after
            feature computation and scoring. Set by the domain assembler
            before the event is submitted to the DecisionLedger framework.
        reasoner_context: Generic reasoner evidence record populated by the
            domain assembler from ScorerOutput and AtoFeatureVector. None
            in intermediate pipeline stages before assembly. The framework
            raises if None at submission time.
        fast_path_rationale: Required when ``route`` is ``FAST_PATH_ALLOW``
            or ``FAST_PATH_BLOCK``. Human-readable explanation of the
            confidence-band rule that fired (e.g., ``"risk_score=0.93 >
            0.85 → FAST_PATH_BLOCK"``). ``None`` when routing to the policy
            gate. The framework raises ``ObservationContractError`` if this
            is absent on a fast-path observation.
        gate_context: Domain-assembled policy gate context. Required on every
            event — including fast-path ones — to enable shadow evaluation.
            Populated by the domain assembler from the event, computed
            features, and scorer output.
        scenario_tag: Generator-only label. Stripped before scoring — never
            reaches the feature layer or scorer.
    """

    model_config = ConfigDict(strict=True, frozen=True)

    # Framework identity fields (satisfy Observation protocol)
    event_id: str
    entity_type: Literal["account"] = "account"
    timestamp: datetime

    # Domain identity
    account_id: str
    session_id: str

    # Network
    ip_address: str
    geolocation: Geolocation

    # Device
    device_fingerprint: str
    user_agent: str

    # Auth context
    auth_method: AuthMethod
    outcome: AuthOutcome

    # Framework Observation fields — set by domain assembler after
    # feature computation and scoring, before framework submission.
    route: GateRoute = GateRoute.ROUTE_TO_GATE
    reasoner_context: ReasonerContext | None = None
    fast_path_rationale: str | None = None
    gate_context: GateContext = GateContext(gate_id="policy")

    # Generator only — stripped before scoring
    scenario_tag: str | None = None

    @computed_field
    @property
    def entity_id(self) -> UUID:
        """Framework UUID derived deterministically from account_id."""
        return uuid.uuid5(_ATO_ACCOUNT_NS, self.account_id)
